name: bmcs_env
channels:
- conda-forge
dependencies:
- appmode
- jupyter_contrib_nbextensions
- traits>=6.1.1
- matplotlib-base
- numpy>=1.19.2
- scipy>=1.5.2
- sympy
- ipywidgets
- ipympl
- pip
- pip:
  - bmcs_utils
  - -e .